### ISSUE TITLE
error when adding some collections

### ISSUE THREAD

**Issue by dt2i** [ghomasHudson/Jellyfin-Auto-Collections#10]
I get a similar error when adding some of my lists--

when adding Looney Toons golden collection ("ls090428174")

Traceback (most recent call last):
  File "/home/david/Downloads/Jellyfin-Auto-Collections/imdb_list.py", line 59, in <module>
    params2["includeItemTypes"] = imdb_to_jellyfin_type_map[item["Title Type"]]
KeyError: 'video'

when adding peanuts tv specials: ("ls025658622")

Traceback (most recent call last):
  File "/home/david/Downloads/Jellyfin-Auto-Collections/imdb_list.py", line 59, in <module>
    params2["includeItemTypes"] = imdb_to_jellyfin_type_map[item["Title Type"]]
KeyError: 'tvShort'

when adding quentin tarantino's 333 favorite movies ("ls043093231")

Traceback (most recent call last):
  File "/home/david/Downloads/Jellyfin-Auto-Collections/imdb_list.py", line 59, in <module>
    params2["includeItemTypes"] = imdb_to_jellyfin_type_map[item["Title Type"]]
KeyError: 'video'

**Comment by ghomasHudson** [comment]
Thanks for raising the issue, it's a little challenging as 'video' is a pretty generic media type (could be a movie or tv show). I'll add it as both but this might lead to lower matching quality.

Try it and see.
