### ISSUE TITLE
Windows config error

### ISSUE THREAD

**Issue by HellBoyJr** [ghomasHudson/Jellyfin-Auto-Collections#32]
Hi, I'm a Windows user. It's giving this error:

> C:\Users\Administrador\Desktop>echo 09/06/2024 ├ás 15:48:24,27  1>>"C:\Users\Administrador\Desktop\Agendados\JAC.txt"
Traceback (most recent call last):
  File "C:\Users\Administrador\Desktop\Jellyfin-Auto-Collections-master\main.py", line 11, in <module>
    config = parse_config('config.yaml', default_value=None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\pyaml_env\parse_config.py", line 110, in parse_config
    return yaml.load(conf_data, Loader=loader)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Python\Lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "config.yaml", line 9, column 41

I'm using this script via .bat:

> cd "C:\Users\Administrador\Desktop\Jellyfin-Auto-Collections-master"
C:\Python\python.exe "C:\Users\Administrador\Desktop\Jellyfin-Auto-Collections-master\main.py" -r

Any suggestions on how it works?  Thanks in advance.

**Comment by mzrimsek** [comment]
Seems like your config YAML might be malformed.

**Comment by HellBoyJr** [comment]
Config yaml:

> jellyfin:

  server_url: !ENV ${JELLYFIN_SERVER_URL: http://localhost:8096}
  api_key: !ENV ${JELLYFIN_API_KEY: c38ea04f0f914c488a*****************}         # Create an API key by going to: Admin>Dashboard>Advanced>API Keys
  user_id: !ENV ${JELLYFIN_USER_ID: 3406f49c344c4***********************}

**Comment by ghomasHudson** [comment]
> Config yaml:
> 
> > jellyfin:
> 
> server_url: !ENV ${JELLYFIN_SERVER_URL: [http://localhost:8096}](http://localhost:8096%7D) api_key: !ENV ${JELLYFIN_API_KEY: c38ea04f0f914c488a*****************} # Create an API key by going to: Admin>Dashboard>Advanced>API Keys user_id: !ENV ${JELLYFIN_USER_ID: 3406f49c344c4***********************}

Hard to tell but looks like there's an extra closing `}` on some of those lines.

**Comment by HellBoyJr** [comment]
It seems normal https://paste.ofcode.org/9MmFxaWRJiZPPx7dMs8MjT

**Comment by ghomasHudson** [comment]
> It seems normal https://paste.ofcode.org/9MmFxaWRJiZPPx7dMs8MjT

Figured it out: You need to remove the spaces after the colons: e.g.

```yaml
server_url: !ENV ${JELLYFIN_SERVER_URL:http://localhost:8096}
api_key: !ENV ${JELLYFIN_API_KEY:c38ea04f0f914c488a*****************} # Create an API key by going to: Admin>Dashboard>Advanced>API Keys
user_id: !ENV ${JELLYFIN_USER_ID:3406f49c344c4***********************}
```

I've updated the config example to reflect this.

**Comment by HellBoyJr** [comment]
Worked perfectly. Thanks again.

**Comment by ghomasHudson** [comment]
No problem - Thanks for raising the issue.
