### ISSUE TITLE
trakt error

### ISSUE THREAD

**Issue by HellBoyJr** [ghomasHudson/Jellyfin-Auto-Collections#35]
Hi, I'm getting this error with trakt list.

> C:\Users\Administrador\Desktop>echo 15/06/2024 ├ás 13:37:52,19  1>>"C:\Users\Administrador\Desktop\Agendados\JAC.txt"
2024-06-15 13:37:52.594 | INFO     | __main__:<module>:43 - Starting up
2024-06-15 13:37:52.594 | INFO     | __main__:<module>:44 - Starting initial run
Traceback (most recent call last):
  File "C:\Jellyfin-Auto-Collections\main.py", line 45, in <module>
    main(config)
  File "C:\Jellyfin-Auto-Collections\main.py", line 23, in main
    plugins = loader.plugins['list_scraper']
  File "C:\Python\lib\site-packages\pluginlib\_loader.py", line 398, in plugins
    self.load_modules()
  File "C:\Python\lib\site-packages\pluginlib\_loader.py", line 366, in load_modules
    _recursive_import(_import_module(mod))
  File "C:\Python\lib\site-packages\pluginlib\_loader.py", line 153, in _recursive_import
    _import_module(name, finder.path)
  File "C:\Python\lib\site-packages\pluginlib\_loader.py", line 133, in _import_module
    _raise_friendly_exception(e, name, path)
  File "C:\Python\lib\site-packages\pluginlib\_loader.py", line 91, in _raise_friendly_exception
    raise_with_traceback(exception, tback)
  File "<string>", line 2, in raise_with_traceback
  File "C:\Python\lib\site-packages\pluginlib\_loader.py", line 130, in _import_module
    mod = epoint.load() if epoint else importlib.import_module(name)
  File "C:\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
pluginlib.exceptions.PluginImportError: Error while importing candidate plugin module plugins.trakt from C:\Jellyfin-Auto-Collections\plugins: SyntaxError("f-string: unmatched '['", ('C:\\Jellyfin-Auto-Collections\\plugins\\trakt.py', 100, 89, '            print(f"Please visit the following URL to get your access token: {r.json()["verification_url"]}")\n', 100, 105))
Pressione qualquer tecla para continuar. . .

**Comment by ghomasHudson** [comment]
Hmm I've not added much error checking to the trakt code yet.

Have you generated a `client_id` and `client_secret` from https://trakt.tv/oauth/applications/new and added them to the config as per the example?

**Comment by HellBoyJr** [comment]
Yes, I already have it.

**Comment by ghomasHudson** [comment]
Ahh spotted it - clearly I didn't test this enough! Should work now.
