### ISSUE TITLE
Letterboxd Lists without release years

### ISSUE THREAD

**Issue by consier** [ghomasHudson/Jellyfin-Auto-Collections#38]
the provided example letterboxd lists work fine.
[aobh/list/written-by-women](https://letterboxd.com/aobh/list/written-by-women/) does not. 
could it be too large?

```2024-06-17 12:47:58.220 | INFO     | __main__:<module>:43 - Starting up
2024-06-17 12:47:58.220 | INFO     | __main__:<module>:44 - Starting initial run
2024-06-17 12:47:58.862 | INFO     | __main__:main:29 - 
2024-06-17 12:47:58.862 | INFO     | __main__:main:30 - 
2024-06-17 12:47:58.862 | INFO     | __main__:main:31 - Getting list info for plugin: letterboxd, list id: aobh/list/written-by-women
Traceback (most recent call last):
  File "/Jellyfin-Auto-Collections/main.py", line 45, in <module>
    main(config)
  File "/Jellyfin-Auto-Collections/main.py", line 32, in main
    list_info = plugins[plugin_name].get_list(list_id, config['plugins'][plugin_name])
  File "/Jellyfin-Auto-Collections/plugins/letterboxd.py", line 29, in get_list
    movie_year = movie_soup.find('small', {'class': 'metadata'}).text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by ghomasHudson** [comment]
Ah, i see the problem. Many movies in that list don't have release dates (either because it isn't know or they're upcoming). It looks like a length issue because all these movies appear at the end when sorted by release year.

I've added some checks for this, so hopefully it works now.
