### ISSUE TITLE
Add Letterboxd Watchlists

### ISSUE THREAD

**Issue by consier** [ghomasHudson/Jellyfin-Auto-Collections#39]
It would be great to add Letterboxd Watchlists.
However, naming could become an issue when adding multiple watchlists as they are always named `watchlist`

```
2024-06-17 16:39:01.196 | INFO     | __main__:<module>:43 - Starting up
2024-06-17 16:39:01.196 | INFO     | __main__:<module>:44 - Starting initial run
2024-06-17 16:39:01.681 | INFO     | __main__:main:29 - 
2024-06-17 16:39:01.681 | INFO     | __main__:main:30 - 
2024-06-17 16:39:01.681 | INFO     | __main__:main:31 - Getting list info for plugin: letterboxd, list id: username/watchlist
Page number:  1
Traceback (most recent call last):
  File "/Jellyfin-Auto-Collections/main.py", line 45, in <module>
    main(config)
  File "/Jellyfin-Auto-Collections/main.py", line 32, in main
    list_info = plugins[plugin_name].get_list(list_id, config['plugins'][plugin_name])
  File "/Jellyfin-Auto-Collections/plugins/letterboxd.py", line 25, in get_list
    list_name = soup.find('h1', {'class': 'title-1 prettify'}).text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by ghomasHudson** [comment]
The watchlists are a different format from the main lists so will require some more substantional reworking to get functional. I'll have a go later this week.

**Comment by samueljim** [comment]
bump on this :) Let me see if i can work this out

**Comment by samueljim** [comment]
https://github.com/ghomasHudson/Jellyfin-Auto-Collections/pull/42/files here is support for watchlists

**Comment by kandykarter** [comment]
Hey fellas, is there a trick to making watchlists work? I just tried it and got effectively the same error as the initial post in this ticket. 

```
 INFO     | plugins.letterboxd:get_list:23 - Page number: 1
 Traceback (most recent call last):
   File "/app/main.py", line 114, in <module>
     main(config)
   File "/app/main.py", line 79, in main
     list_info = plugins[plugin_name].get_list(list_id, config['plugins'][plugin_name])
   File "/app/plugins/letterboxd.py", line 44, in get_list
     list_name = soup.find('h1', {'class': 'title-1 prettify'}).text
 AttributeError: 'NoneType' object has no attribute 'text'
```

Edit: It was a trailing slash. Regular lists are fine with a trailing slash, removing it from the watchlist line solved the issue.
