### ISSUE TITLE
Error after updating to 10.9.8

### ISSUE THREAD

**Issue by BoHoliday** [ghomasHudson/Jellyfin-Auto-Collections#50]
```
2024-08-03 04:32:06.989 | INFO     | __main__:<module>:48 - Starting up
2024-08-03 04:32:06.989 | INFO     | __main__:<module>:49 - Starting initial run
2024-08-03 04:32:07.029 | INFO     | __main__:main:34 - 
2024-08-03 04:32:07.029 | INFO     | __main__:main:35 - 
2024-08-03 04:32:07.030 | INFO     | __main__:main:36 - Getting list info for plugin: imdb_chart, list id: moviemeter
Traceback (most recent call last):
  File "/app/main.py", line 50, in <module>
    main(config)
  File "/app/main.py", line 37, in main
    list_info = plugins[plugin_name].get_list(list_id, config['plugins'][plugin_name])
  File "/app/plugins/imdb_chart.py", line 30, in get_list
    release_year = movie["releaseYear"]["year"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ghomasHudson** [comment]
Thanks for finding this - I'll update myself and fix things.

**Comment by ghomasHudson** [comment]
This looks like an error in the imdb list parsing not the jellyfin server version.

**Comment by ghomasHudson** [comment]
I couldn't reproduce the error - Maybe it was just a specific movie that had no release year. I've added some more error checking around this to prevent it thowing errors now.

**Comment by king8084** [comment]
i am getting thse errors, even if i remove all imdb lists except one, still getting them
